name: unihr
description: HR Management For Permanent Employee.

version: 2.2.2+81

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.1
  google_fonts: ^6.1.0
  get_it: ^7.6.7
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  flutter_svg: ^2.0.10+1
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  syncfusion_flutter_charts: ^24.2.8
  swipeable_tile: ^2.0.0+3
  expand_widget: ^3.1.1
  badges: ^3.1.2
  slide_digital_clock: ^1.0.3
  maps_toolkit: ^3.0.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  month_picker_dialog: ^2.11.0
  table_calendar: ^3.0.9
  day: ^0.8.0
  pdf: ^3.10.8
  path_provider: ^2.1.2
  open_file: ^3.3.2
  printing: ^5.12.0
  expandable_page_view: ^1.0.17
  loading_animation_widget: ^1.2.0+4
  searchfield: ^0.9.2
  location: ^5.0.3
  geocoding: ^2.2.0
  pinput: ^4.0.0
  dio: ^5.4.1
  logger: ^2.0.2+1
  quickalert: ^1.0.2
  flutter_blue_plus: ^1.31.15
  permission_handler: ^11.3.0
  simple_gradient_text: ^1.3.0
  upgrader: ^9.0.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  readmore: ^2.2.0
  image_card: ^0.0.4
  percent_indicator: ^4.2.3
  avatar_stack: ^1.2.0
  shimmer: ^3.0.0
  chips_choice: ^3.0.1
  buttons_tabbar: ^1.3.8
  multiple_search_selection: ^2.6.2
  device_info_plus: ^9.1.2
  mask_text_input_formatter: ^2.9.0
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  restart_app: ^1.2.1
  flutter_localizations:
    sdk: flutter
  quiver: ^3.2.1
  in_app_update: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/uni_app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/employees_list_manager/
    - assets/images/learning_user/
    - assets/icons/
    - assets/icons/overview_manager/
    - assets/icons/learning_user/
    - assets/gifs/

  fonts:
    - family: kanit
      fonts:
        - asset: assets/google_fonts/Kanit-Regular.ttf
